[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HYPRE = "b5ffcf37-a2bd-41ab-a3da-4bd9bc8ad771"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JOLI = "bb331ad6-a1cf-11e9-23da-9bcb53c69f6f"
JSONRPC = "b9b8584e-8fd3-41f9-ad0c-7255d428e418"
JUDI = "f3b833dc-6b2e-5b9c-b940-873ed6319979"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SegyIO = "157a0f19-4d44-4de5-a0d0-07e2f0ac4dfa"
SlimOptim = "e4c7bc62-5b23-4522-a1b9-71c2be45f1df"
SlimPlotting = "f6d04670-764e-495b-a720-91c3c9a588ff"
StaticLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"

[compat]
julia = "1.11"

